---
- name: PLAYBOOK1
  hosts: bigips
  connection: local
  gather_facts: false

  vars:
    uri_method: POST

  vars_files:
  - ../credentials/bigip.yaml

  tasks:
  
  - name: AS3 Deploy
    uri:
      url: "https://{{inventory_hostname}}/mgmt/shared/appsvcs/declare/"
      user: "{{bigip_user}}"
      password: "{{bigip_pass}}" 
      method: "{{uri_method}}"
      body: "{{ lookup('file','as3-declaration.json') }}"
      force_basic_auth: true
      body_format: json
      validate_certs: false
      status_code:
        - 200
        - 204
    register: as3_response    
    delay: 30
    retries: 5
    until: ( 'status' in as3_response and (as3_response.status == 200 or as3_response.status == 204 ))
    changed_when: false

  - name: AS3 Deploy Debug Output
    debug:
      msg: "{{as3_response.json.declaration}}"
...